language: node_js
node_js:
- '12'
branches:
  only:
  - deploy
install:
- npm install -g @nestjs/cli
script:
- npm ci
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: Oag88hB91rcmFgtCoOEz5NWq2vqRHKT/RznjbiA0Jh42CsRg4oO8O10ArCl/H7WGN9mPmC4a8UPg9kzyenLU6Cs5SEVAwgYCWFlIHWl/hGi4cNgsu1f1jUePdH6pf2jFOaXmQadrFzPCZ3FKSPOOQBIvhCD9Yi6GDe+C5cJEktgGGtdgoy1D0CN5jsCuUIXj67oV2uTvRlQWyX9u2C5BES4lHwkKRXXpyVl2kSEvVKi7mJ2Q2x4cV+9HwLYCnk72emaPPIKGGwGrRMyEkE1dQqCZdj/ItnIjKTbTVYpZ+qQqs/NEkUjZyRhJRDzZPe4OEEdKXipGZntp8zTTTc+iStsP5XYtvwUT9vDblyE9R+eAsiIzqVBvk/3UvUEODMI+Si+vXpXqrQX9jdAvnq1NJCOY9RdsASZBKIxz++JnYV9WrPtWqpq8Nu+etN4V2GVbHhv8/iFelYudyWVR876qMdwsjpzg8/Z1J7iA1PtIYJdy2YWTr6kvxxn6pBrrLhqLs2Uf3cLD4J8n5kOuCY8AyZI+f5EvudnZSkm/Q3kCaU1dmjx6/5LrPYo78KpOmuTXC43rTaIFcq/h1ftY/GPqH7ZQI0r8LBPljqtFQXYFbUbgdswLkGtNyyFuJM58LKPBxXsREikfdT09rPR4EfAAiyMhl0vqriBzQU4DWfXEzaU=
  app: cnc-trivia-api
  on: deploy
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: dist/*
